env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - standard
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
globals:
  chrome: true
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
settings:
  react:
    version: 'detect'
rules: {
  'react/display-name': 'off',
  'no-use-before-define': 'off',
  '@typescript-eslint/no-use-before-define': 'error',
  'no-unused-vars': 'off',
  '@typescript-eslint/no-unused-vars': 'error'
}
